"""create generated_contents table

Revision ID: fc789ff08f13
Revises: fece811807d1
Create Date: 2025-07-07 14:30:31.316857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc789ff08f13'
down_revision = 'fece811807d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_item_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('summary', 'flashcards', 'qa', name='content_format_enum'), nullable=False),
    sa.Column('length', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['library_item_id'], ['library_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_contents_id'), 'generated_contents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_contents_id'), table_name='generated_contents')
    op.drop_table('generated_contents')
    # ### end Alembic commands ###
