"""add library_items table

Revision ID: fece811807d1
Revises: 1705343aba7a
Create Date: 2025-07-07 14:26:10.630885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fece811807d1'
down_revision = '1705343aba7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url_or_path', sa.String(), nullable=False),
    sa.Column('content_type', sa.Enum('url', 'pdf', name='contenttype'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_items_id'), 'library_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_library_items_id'), table_name='library_items')
    op.drop_table('library_items')
    # ### end Alembic commands ###
